// Copies static/index.html into page.js, a normal JavaScript module.
// Vercel always bundles required modules, while loose folders like static/ can be left out.
// Runs automatically before `npm start`. Run it again (npm run build-page) before you commit
// and push, if you changed static/index.html.
const fs = require("fs");
const path = require("path");

const src = path.join(__dirname, "..", "static", "index.html");
const out = path.join(__dirname, "..", "page.js");

if (!fs.existsSync(src)) {
  console.warn("build-page: static/index.html not found, keeping the existing page.js");
  process.exit(0);
}
const html = fs.readFileSync(src, "utf8");
fs.writeFileSync(
  out,
  "// Generated from static/index.html by scripts/build-page.js. Do not edit this file.\n" +
    "module.exports = " + JSON.stringify(html) + ";\n"
);
console.log("build-page: wrote page.js (" + html.length + " characters)");